- name: Bootstrap server
  hosts: frt.duckdns.org
  roles:
    - role: packages
      vars:
        packages_uninstall:
          - ufw
          - smartmontools
          - wpasupplicant
        packages_install:
          - iptables
          - iptables-persistent
    - sshd

